services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
      target: airflow
      args:
        # These args are used during the build but do not persist into the container
        AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES}
        AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: ${AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS}
        AIRFLOW__CORE__DAGS_FOLDER: ${AIRFLOW__CORE__DAGS_FOLDER}
        AIRFLOW__CORE__STORE_SERIALIZED_DAGS: ${AIRFLOW__CORE__STORE_SERIALIZED_DAGS}
        AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: ${AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL}
        AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: ${AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL}
        AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL: ${AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL}
        AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL: ${AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL}
        AIRFLOW_USER_USERNAME: ${AIRFLOW_USER_USERNAME}
        AIRFLOW_USER_PASSWORD: ${AIRFLOW_USER_PASSWORD}
        AIRFLOW_USER_EMAIL: ${AIRFLOW_USER_EMAIL}
        AIRFLOW_USER_FIRSTNAME: ${AIRFLOW_USER_FIRSTNAME}
        AIRFLOW_USER_LASTNAME: ${AIRFLOW_USER_LASTNAME}
        AIRFLOW_USER_ROLE: ${AIRFLOW_USER_ROLE}

    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/airflow-image:latest
    ports:
      - "8080:8080"
