services:
  airflow:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/airflow-image:latest
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=True
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=5
      - AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL=5
      - AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL=10
      - AIRFLOW__CORE__MIN_SERIALIZED_DAG_FETCH_INTERVAL=10
      - AIRFLOW_USER_USERNAME=admin
      - AIRFLOW_USER_PASSWORD=admin
      - AIRFLOW_USER_EMAIL=admin@example.com
      - AIRFLOW_USER_FIRSTNAME=Admin
      - AIRFLOW_USER_LASTNAME=User
      - AIRFLOW_USER_ROLE=Admin
      #- RUNNING_IN_AWS_ECS=False
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5