name: Upload Dags

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - 'dags/**/*.py'

jobs:
  upload_dags:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Upload all .py files in dags folder
        run: |
          for file in $(find dags/ -name '*.py'); do
            echo "Uploading $file"
            python subirDAG.py "$file"
          done
