name: Upload Modified Dags

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'

jobs:
  upload_dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo el historial

      - name: Install dependencies
        run: pip install requests

      - name: Get list of modified files
        id: get_modified_files
        run: |
          # Obtiene la lista de archivos modificados en el último commit
          MODIFIED_FILES=$(git diff --name-only HEAD^ HEAD -- 'dags/**')
          echo "Archivos modificados: $MODIFIED_FILES"
          echo "files=$MODIFIED_FILES" >> $GITHUB_OUTPUT

      - name: Upload modified files
        if: steps.get_modified_files.outputs.files != ''
        run: |
          for file in ${{ steps.get_modified_files.outputs.files }}; do
            echo "Uploading $file"
            python subirDAG.py "$file"
          done

