name: Upload All Dags

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**/*.py'  # Solo archivos .py en la carpeta dags

jobs:
  upload_dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Concatenate .md files into readme.md
        run: |
          rm -f readme.md
          for file in $(find dags/ -name '*.md'); do
            filename=$(basename "$file" .md)
            echo "#$filename:" >> readme.md
            cat "$file" >> readme.md
            echo "" >> readme.md  # Añade una línea en blanco para separar
          done

      - name: Upload all .py files in dags folder
        run: |
          for file in $(find dags/ -name '*.py'); do
            echo "Uploading $file"
            python subirDAG.py "$file"
          done
